[package]
name = "cdshealpix_libpgsql"
version = "0.1.0"
authors = ["F.-X. Pineau <francois-xavier.pineau@astro.unistra.fr>"]

[build-dependencies]
cdshealpix ="0.6"

[dependencies]
libc = "*"
cdshealpix = "0.6"


[lib]
name = "cdshealpix_libpsql"
path = "src/lib.rs"
crate-type = ["staticlib"]

